# Generated by Django 3.2.3 on 2021-06-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='nombreArtista',
            field=models.CharField(max_length=30, verbose_name='Artista'),
        ),
    ]
