# Generated by Django 3.2.3 on 2021-06-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_obra_nombreartista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idMensajes', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombreAsuntos', models.IntegerField(max_length=60, verbose_name='Asunto')),
                ('nombreMensaje', models.IntegerField(max_length=100, verbose_name='Mensaje')),
            ],
        ),
    ]
