# Generated by Django 3.2.3 on 2021-06-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombreAsuntos',
            field=models.IntegerField(max_length=50, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombreMensaje',
            field=models.IntegerField(max_length=50, verbose_name='Mensaje'),
        ),
    ]
